# Makefile

all: Display.java Render.java Screen.java Game.java
	javac Display.java
	javac Render.java
	javac Screen.java
	javac Game.java

clean:
	rm -vf Display.class
	rm -vf Render.class
	rm -vf Screen.class
	rm -vf Game.class
