# Makefile

all: Display.java Render.java Screen.java Game.java Render3D.java
	javac Display.java
	javac Render.java
	javac Screen.java
	javac Game.java
	javac Render3D.java

clean:
	rm -vf Display.class
	rm -vf Render.class
	rm -vf Screen.class
	rm -vf Game.class
	rm -vf Render3D.class
